# Generated by Django 5.2.6 on 2025-09-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='projects/')),
                ('MovieID', models.PositiveIntegerField()),
                ('MovieTitle', models.CharField(max_length=50)),
                ('Actor1Name', models.CharField(max_length=25)),
                ('Actor2Name', models.CharField(max_length=25)),
                ('DirectorName', models.CharField(max_length=50)),
                ('MovieGenre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Musical', 'Musical'), ('Anime', 'Anime')])),
                ('ReleaseYear', models.PositiveIntegerField()),
            ],
        ),
    ]
